version: '3'

services:

  minio:
    image: minio/minio
    container_name: minio
    expose:
      - 9000    
    volumes:
      - ./notea-data:/data
    restart: unless-stopped      
    environment:
      MINIO_ACCESS_KEY: Gg0Dz157x7JDz3icpJ5HXiRcvQ
      MINIO_SECRET_KEY: ZSCRkEcLXidts2h8XFfja7a2zFuvEUCRimASUivJcEzfaHcQ
    entrypoint: sh
    command: -c 'mkdir -p /data/notea && mkdir -p /data/notea-test && minio server /data'

  
  notea:
    image: cinwell/notea:main
    container_name: notea
    ports:
      - 8200:3000
    restart: unless-stopped      
    environment:
      STORE_ACCESS_KEY: Gg0Dz157x7JDz3icpJ5HXiRcvQ
      STORE_SECRET_KEY: ZSCRkEcLXidts2h8XFfja7a2zFuvEUCRimASUivJcEzfaHcQ
      STORE_BUCKET: notea
      STORE_END_POINT: http://minio:9000
      STORE_FORCE_PATH_STYLE: "true"
      PASSWORD: p4ssw0rd
      COOKIE_SECURE: "false"
      BASE_URL: http://localhost:8200/
    depends_on:
      - minio
